server:
  port: ${PORT:0}

spring:
  application:
    name: api-catalog
  zipkin:
    base-url: http://localhost:9411/
    enabled:true

info:
  application:
    name: api-catalog

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
